spring:
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/conference_app?useSSL=false&allowPublicKeyRetrieval=true
    schemas: conference_app
    user: conference_app
    password: c0nf3r3nc3_@pp
  datasource:
    url: jdbc:mysql://localhost:3306/conference_app?useSSL=false&allowPublicKeyRetrieval=true
    username: conference_app
    password: c0nf3r3nc3_@pp
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none