spring:
  flyway:
    enabled: true
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    schemas: ${DB_NAME}
    user: conference_app
    password: c0nf3r3nc3_@pp
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: conference_app
    password: c0nf3r3nc3_@pp
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
---
spring:
  profiles: prod
logging:
  level:
    org: WARN